apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac-role.yaml
  - rbac-rolebinding.yaml
  - service.yaml
  - deployment.yaml
