apiVersion: v1
kind: Service
metadata:
  name: gke-fastapi-prod-svc
  namespace: gke-fastapi-prod
spec:
  selector:
    app: gke-fastapi-prod
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
