apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

patches:
  - path: gcp.yaml
    target:
      kind: Deployment
      name: gke-fastapi-prod
      namespace: gke-fastapi-prod
